[general]
import = ["./nord.toml"]

[env]
TERM = 'alacritty'

[window]
padding = { x = 8, y = 8 }
dynamic_title = false
title = ""

[font]
normal = { family = "IosevkaMgjTerm Nerd Font", style = "SemiExtended" }
bold = { family = "IosevkaMgjTerm Nerd Font", style = "SemiExtended Bold" }
italic = { family = "IosevkaMgjTerm Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaMgjTerm Nerd Font", style = "Bold Italic" }
size = 12.0

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"
