[user]
name = "marcos-x0"
email = "192031541+marcos-x0@users.noreply.github.com"

[snapshot]
auto-update-stale = true
# [git]
# push-new-bookmarks = true
# "(heads(@::) | heads(@::)- | heads(@::)-- | heads(@::)--- | @+++ | @++ | @ | @- | @-- | @--- | (trunk()+ & mine()) | trunk())",

[ui]
default-command = [
  "log",
  "-r",
  '(heads(@::) ~ (working_copies() ~ @)) | (heads(@::) ~ (working_copies() ~ @))- | roots(::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root())) | coalesce(trunk(), root()) | (bookmarks() | bookmarks()+) & (::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root())) | (@ | @+ | @-)',
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  commit_timestamp(self).ago(),

                  bookmarks,
                  tags,
                  working_copies,
                  if(conflict, label("conflict", "conflict")),
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                ),
              ),
            )
          )
''',
]

# default-command = ["log", "-r", "(::@ | @::) ~(::trunk())-"]
editor = "nvim"
pager = "delta"


conflict-marker-style = "git"
# diff-editor = "gitpatch"

# [merge-tools.gitpatch]
# program = "sh"
# edit-args = [
#   "-c",
#   '''
#   set -eu
#   rm -f "$right/JJ-INSTRUCTIONS"
#   git -C "$left" init -q
#   git -C "$left" add -A
#   git -C "$left" commit -q -m baseline --allow-empty
#   mv "$left/.git" "$right"
#   git -C "$right" add --intent-to-add -A
#   git -C "$right" add -p
#   git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
#   git -C "$right" commit -q -m split
#   git -C "$right" restore . # undo changes in modified files
#   git -C "$right" reset .   # undo --intent-to-add
#   git -C "$right" clean -q -df # remove untracked files
# ''',
# ]

merge-tool = "vimdiff"

[merge-tools.vimdiff]
merge-args = [
  "-f",
  "-d",
  "$output",
  "-M",
  "$left",
  "$base",
  "$right",
  "-c",
  "wincmd J",
  "-c",
  "set modifiable",
  "-c",
  "set write",
]

program = "nvim"
merge-tool-edits-conflict-markers = true

[merge-tool.git]
program = "git"
args = ["merge-file", "--diff3", "$left", "$base", "$right", "-p"]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'


[aliases]
# lla = ["log", "-r", "all() & ~remote_bookmarks()", "-T", '''
lla = ["log", "-r", "all()", "-T", '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  commit_timestamp(self).format("%Y-%m-%d %H:%M:%S"),
                  author.email().local(),

                  bookmarks,
                  tags,
                  working_copies,
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                  format_short_change_id_with_change_offset(self),
                  format_short_commit_id(commit_id),

                ),
              ),
            )
          )
''']

# if(conflict, label("conflict", "conflict")),

l = [
  "log",
  "-r",
  "::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()) | coalesce(trunk(), root())",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  commit_timestamp(self).ago(),

                  bookmarks,
                  tags,
                  working_copies,
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                  format_short_change_id_with_change_offset(self),

                ),
              ),
            )
          )
''',
]

ll = [
  "log",
  # "-r",
  # "(all() & ~remote_bookmarks() & ~ancestors(trunk()))",
  # "all() & ~remote_bookmarks() & (trunk() | root() | descendants(trunk() | root()))",
  # "descendants(trunk() | root()) & ~remote_bookmarks()",
  # "all() & ~remote_bookmarks() & ~ancestors(trunk(), 1)",
  # "all() & ~remote_bookmarks() & ~ancestors(trunk())",
  "-r",
  # "trunk() | root()",
  "(::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()) & mine()) | coalesce(trunk(), root()) | (((::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()) | coalesce(trunk(), root()))+) ~ (::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()) | coalesce(trunk(), root())) & mine())",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  commit_timestamp(self).format("%Y-%m-%d %H:%M:%S"),

                  bookmarks,
                  tags,
                  working_copies,
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                  format_short_change_id_with_change_offset(self),
                  format_short_commit_id(commit_id),

                ),
              ),
            )
          )
''',
]

la = [
  "log",
  "-r",
  # "(all() & ~remote_bookmarks() & ~ancestors(trunk() | root())) | (trunk() | root()) ~ (trunk();;,",

  # "all() & ~remote_bookmarks() & ~ancestors(trunk(), 1)",
  "mine() | trunk() | root()",
  # "all() & ~remote_bookmarks() & ~ancestors(trunk(), 1) & descendants(trunk()--)",
  # "-r",
  # "trunk()",
  "--limit",
  "1000",

  # "((::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()))) | coalesce(trunk(), root()) | (((::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()) | coalesce(trunk(), root()))+) ~ (::(heads(@::) ~ (working_copies() ~ @)) ~ ::coalesce(trunk(), root()) | coalesce(trunk(), root())))",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  commit_timestamp(self).format("%Y-%m-%d %H:%M:%S"),

                  bookmarks,
                  tags,
                  working_copies,
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                  format_short_change_id_with_change_offset(self),
                  format_short_commit_id(commit_id),

                ),
              ),
            )
          )
''',
]


lt = [
  "log",
  "-r",
  # "team() & ::trunk() & committer_date(after:'2025-09-01')",
  "::trunk() & committer_date(after:'2025-09-01')",
  "--limit",
  "1000",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  commit_timestamp(self).format("%Y-%m-%d %H:%M:%S"),
                  author.email().local(),

                  bookmarks,
                  tags,
                  working_copies,
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                  format_short_change_id_with_change_offset(self),
                  format_short_commit_id(commit_id),

                ),
              ),
            )
          )
''',
]

# lta = [
#   "log",
#   "-r",
#   "team() & committer_date(after:'2025-09-01') | trunk()",
#   "--limit",
#   "1000",
#   "-T",
#   '''
#         if(root,
#             format_root_commit(self),
#             label(if(current_working_copy, "working_copy"),
#               concat(
#                 separate(" ",
#                   format_short_change_id_with_change_offset(self),
#                   commit_timestamp(self).format("%Y-%m-%d %H:%M:%S"),
#                   author.email().local(),
#
#                   bookmarks,
#                   tags,
#                   working_copies,
#                   if(config("ui.show-cryptographic-signatures").as_boolean(),
#                     format_short_cryptographic_signature(signature)),
#                   if(empty, label("empty", "(empty)")),
#                   if(description,
#                     description.first_line(),
#                     label(if(empty, "empty"), description_placeholder),
#                   ),
#                   format_short_change_id_with_change_offset(self),
#                   format_short_commit_id(commit_id),
#
#                 ),
#               ),
#             )
#           )
# ''',
# ]
#

ls = [
  "log",
  "-r",
  "(heads(@::) | heads(@::)- | heads(@::)-- | heads(@::)--- | @ | @- | @-- | @---) | (trunk() | trunk()+ | trunk()++ | trunk()+++)",
]

lx = [
  "log",
  "-r",
  "conflicts() & (::@ | @::)",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_change_offset(self),
                  format_short_commit_id(commit_id),
                  commit_timestamp(self).ago(),
                  bookmarks,
                  tags,
                  working_copies,
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description.first_line().substr(0, 32) == description.first_line(),
                    description.first_line(),
                    description.first_line().substr(0, 31) ++ "â€¦",
                  ),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                ),
              ),
            )
          )
''',
]


e = ["edit"]
d = ["describe", "-m"]
u = ["undo"]
rx = ["resolve", "--tool", "vimdiff"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

c = ["commit", "-m"]
ci = ["commit", "--interactive"]
i = ["git", "init", "--colocate"]
nb = ["bookmark", "create", "-r @-"] # "new bookmark"
# pull = ["git", "fetch"]
# push = ["git", "push", "--allow-new"]
r = ["rebase"]
ra = ["rebase", "-s", "all:roots(trunk()..mutable())", "-d", "trunk"]
rb = ["rebase", "-s", "all:roots(trunk()..mutable()) & mine()", "-d", "trunk"]
s = ["squash"]
si = ["squash", "--interactive"]

fc = ["diff", "--summary"]
ds = ["diff", "--stat"]
