[user]
name = "marcox-x0"
email = "56_despots_parsnip@icloud.com"

# [git]
# push-new-bookmarks = true

[ui]
default-command = [
  "log",
  "-r",
  "(heads(@::) | heads(@::)- | heads(@::)-- | heads(@::)--- | @+++ | @++ | @ | @- | @-- | @--- | trunk())",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_hidden_and_divergent_info(self),
                  commit_timestamp(self).ago(),

                  bookmarks,
                  tags,
                  working_copies,
                  if(git_head, label("git_head", "git_head()")),
                  format_short_commit_id(commit_id),
                  if(conflict, label("conflict", "conflict")),
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                ),
              ),
            )
          )
''',
] # default-command = ["log", "-r", "(::@ | @::) ~(::trunk())-"]
editor = "nvim"
pager = "delta"


conflict-marker-style = "git"
diff-editor = "gitpatch"

[merge-tools.gitpatch]
program = "sh"
edit-args = [
  "-c",
  '''
  set -eu
  rm -f "$right/JJ-INSTRUCTIONS"
  git -C "$left" init -q
  git -C "$left" add -A
  git -C "$left" commit -q -m baseline --allow-empty
  mv "$left/.git" "$right"
  git -C "$right" add --intent-to-add -A
  git -C "$right" add -p
  git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
  git -C "$right" commit -q -m split
  git -C "$right" restore . # undo changes in modified files
  git -C "$right" reset .   # undo --intent-to-add
  git -C "$right" clean -q -df # remove untracked files
''',
]

merge-tool = "vimdiff"

[merge-tools.vimdiff]
merge-args = [
  "-f",
  "-d",
  "$output",
  "-M",
  "$left",
  "$base",
  "$right",
  "-c",
  "wincmd J",
  "-c",
  "set modifiable",
  "-c",
  "set write",
]
program = "nvim"
merge-tool-edits-conflict-markers = true

[merge-tool.git]
program = "git"
args = ["merge-file", "--diff3", "$left", "$base", "$right", "-p"]

[aliases]
l = ["log", "-r", "(::@ | @::) ~(::trunk())- | trunk()::", "-T", '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_hidden_and_divergent_info(self),
                  commit_timestamp(self).ago(),

                  bookmarks,
                  tags,
                  working_copies,
                  if(git_head, label("git_head", "git_head()")),
                  format_short_commit_id(commit_id),
                  if(conflict, label("conflict", "conflict")),
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                ),
              ),
            )
          )
''']

ls = [
  "log",
  "-r",
  "(heads(@::) | heads(@::)- | heads(@::)-- | heads(@::)--- | @ | @- | @-- | @---) | (trunk() | trunk()+ | trunk()++ | trunk()+++)",
]

lx = [
  "log",
  "-r",
  "conflicts() & @::",
  "-T",
  '''
        if(root,
            format_root_commit(self),
            label(if(current_working_copy, "working_copy"),
              concat(
                separate(" ",
                  format_short_change_id_with_hidden_and_divergent_info(self),
                  commit_timestamp(self).ago(),
                  bookmarks,
                  tags,
                  working_copies,
                  if(git_head, label("git_head", "git_head()")),
                  format_short_commit_id(commit_id),
                  if(config("ui.show-cryptographic-signatures").as_boolean(),
                    format_short_cryptographic_signature(signature)),
                  if(empty, label("empty", "(empty)")),
                  if(description.first_line().substr(0, 32) == description.first_line(),
                    description.first_line(),
                    description.first_line().substr(0, 31) ++ "…",
                  ),
                  if(description,
                    description.first_line(),
                    label(if(empty, "empty"), description_placeholder),
                  ),
                ),
              ),
            )
          )
''',
]


e = ["edit"]
d = ["describe", "-m"]
u = ["undo"]
rx = ["resolve", "--tool", "vimdiff"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

c = ["commit", "-m"]
ci = ["commit", "--interactive"]
i = ["git", "init", "--colocate"]
nb = ["bookmark", "create", "-r @-"] # "new bookmark"
# pull = ["git", "fetch"]
# push = ["git", "push", "--allow-new"]
r = ["rebase"]
ra = ["rebase", "-s", "all:roots(trunk()..mutable())", "-d", "trunk"]
rb = ["rebase", "-s", "all:roots(trunk()..mutable()) & mine()", "-d", "trunk"]
s = ["squash"]
si = ["squash", "--interactive"]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
