diff-editor = "dif diff"

[user]
name = "marcox-x0"
email = "56_despots_parsnip@icloud.com"

[ui]
pager = "delta"
default-command = ["log", "-r", "(::@ | @::) ~(::trunk())-"]
conflict-marker-style = "git"
diff-editor = ":builtin"

[merge-tools.vimdiff]
merge-args = [
  "-f",
  "-d",
  "$output",
  "-M",
  "$left",
  "$base",
  "$right",
  "-c",
  "wincmd J",
  "-c",
  "set modifiable",
  "-c",
  "set write",
]
program = "nvim"
merge-tool-edits-conflict-markers = true

[aliases]
l = ["log"]
e = ["edit"]
d = ["describe", "-m"]
u = ["undo"]

[merge-tool.git]
program = "git"
args = ["merge-file", "--diff3", "$left", "$base", "$right", "-p"]
