format = """
$os\
$username\
$hostname\
$git_metrics\
$directory\
${custom.jj}\
${custom.git_branch}\
${custom.git_state}\
${custom.git_status}\
$cmd_duration\
$line_break\
$python\
$character"""


[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = true
fish_style_pwd_dir_length = 0

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"

[git_branch]
disabled = true
format = "[$branch]($style)"
style = "#A3BE8C"

[git_status]
disabled = true
format = "[($conflicted$untracked[$staged](#A3BE8C)[$modified$renamed](#EBCB8B)[$deleted](#BF616A)$stashed$diverged)]($style) [($ahead_behind)]() "
style = "cyan"
conflicted = " ${count}"
ahead = " ▲${count}"
behind = " ▼${count}"
untracked = " ?${count}"
modified = " !${count}"
staged = " +${count}"
renamed = " »${count}"
deleted = " x${count}"
stashed = " *${count}"
diverged = '⇕▲${ahead_count}▼${behind_count}'

[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[os]
format = "[$symbol]($style) "
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[custom.git_branch]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_branch"

[custom.git_state]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_state"

[custom.git_status]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_status"


[custom.jj]
command = '$HOME/.local/bin/repo-prompt.bash'
format = "[$symbol](blue bold) $output "
symbol = "\ue702"
when = "jj root --ignore-working-copy"
