# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima", restart_service: :changed
# Pack, ship and run any application as a lightweight container
brew "docker"
# Git-compatible distributed version control system
brew "jj"
# Development kit for the Java programming language
brew "openjdk", link: true
# Development kit for the Java programming language
brew "openjdk@17"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
npm "firebase-tools"
npm "npm-check-updates"
npm "pnpm"
npm "typescript-language-server"
